### ISSUE TITLE
wordConfig.js中敏感词首字符相同时如何处理？

### ISSUE THREAD

**Issue by shuidong** [NextZeus/fuckword#1]
wordConfig.js中把敏感词逐字拆开从而建立key-value,
比如 ABC, MND两个词变成：
a : { b : { c : fuck : 1}},
m : { n : { d : fuck : 1}},
但是如果 首字符相同的情况下怎么办? 
比如
ABC, AND

**Comment by NextZeus** [comment]
首字母相同，应该是
a : { b: { c: {fuck: 1}}, n: {d: {fuck: 1 } } }
